// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nksmcqnekcsxblxbwguf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rc21jcW5la2NzeGJseGJ3Z3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODU3NzQsImV4cCI6MjA2NDQ2MTc3NH0.5gOUo-fk9BwG9e9uhokGfUM2vX3OCLCTuoZWSa0QNDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);